## Домашнее задание

В этой тетрадке вам предлагается реализовать задания при помощи библиотеки numpy. Крайне желательно при выполнении разных заданий не использовать циклы. Если вы не понимаете, как выполнить конкретную задачу без циклов - убирайте их постепенно, разбейте выполнение задачи на этапы и постепенно векторизуйте каждый этап.

Если вам непонятно, как выполнить ту или иную операцию - не стесняйтесь гуглить, если над вами повис дедлайн, а вы всё ещё на чём-то застряли - пишите преподу/в чат, это ок.

**Обсудить решение лучше и сделать в итоге хоть что-то гораздо лучше, чем скатать чужой код или сдать пустую тетрадку.**

In [ ]:
import numpy as np

### Drill (1 балл)

Задание 1.

Инициализируйте нулями массивы следующих форм:

* (5)
* (5, 1)
* (10, 2)
* (3, 6, 2)
* (4, 3, 2, 1)

In [ ]:
one = np.zeros((5))
two = np.zeros((5, 1))
three = np.zeros((10, 2))
four = np.zeros((3, 6, 2))
five = np.zeros((4, 3, 2, 1))

print(one, "\n------------")
print(two, "\n------------")
print(three, "\n------------")
print(four, "\n------------")
print(five, "\n------------")

[0. 0. 0. 0. 0.] 
------------
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]] 
------------
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] 
------------
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]] 
------------
[[[[0.]
   [0.]]

  [[0.]
   [0.]]

  [[0.]
   [0.]]]


 [[[0.]
   [0.]]

  [[0.]
   [0.]]

  [[0.]
   [0.]]]


 [[[0.]
   [0.]]

  [[0.]
   [0.]]

  [[0.]
   [0.]]]


 [[[0.]
   [0.]]

  [[0.]
   [0.]]

  [[0.]
   [0.]]]] 
------------


Задание 2.

Инициализируйте единицами массивы таких же форм и приведите их к целочисленному виду:

In [ ]:
one = np.ones((5), dtype=int)
two = np.ones((5, 1), dtype=int)
three = np.ones((10, 2), dtype=int)
four = np.full((3, 6, 2), 1, dtype=int) # 1 - элемент, который мы используем по умолчанию при инициализации. Для разнообразия:)
five = np.ones((4, 3, 2, 1), dtype=int)

print(one, "\n------------")
print(two, "\n------------")
print(three, "\n------------")
print(four, "\n------------")
print(five, "\n------------")

[1 1 1 1 1] 
------------
[[1]
 [1]
 [1]
 [1]
 [1]] 
------------
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]] 
------------
[[[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]]] 
------------
[[[[1]
   [1]]

  [[1]
   [1]]

  [[1]
   [1]]]


 [[[1]
   [1]]

  [[1]
   [1]]

  [[1]
   [1]]]


 [[[1]
   [1]]

  [[1]
   [1]]

  [[1]
   [1]]]


 [[[1]
   [1]]

  [[1]
   [1]]

  [[1]
   [1]]]] 
------------


Задание 3.

Выполните для векторов выше `reshape` в "форму"
* с двумя компонентами
* с тремя компонентами
* с четырьмя компонентами

In [ ]:
print("One\n------------")
one = one.reshape((5, 1))
print(one, "\n-----")
one = one.reshape((5, 1, 1))
print(one, "\n-----")
one = one.reshape((5, 1, 1, 1))
print(one, "\n------------")

print("Two\n------------")
two = two.reshape((1, 5))
print(two, "\n-----")
two = two.reshape((1, 5, 1))
print(two, "\n-----")
two = two.reshape((1, 1, 1, 5))
print(two, "\n------------")

print("Three\n------------")
three = three.reshape((20, 1))
print(three, "\n-----")
three = three.reshape((1, -1, 2))
print(three, "\n-----")
three = three.reshape((1, 1, 2, -1))
print(three, "\n------------")

print("Four\n------------")
four = four.reshape((3, 12))
print(four, "\n-----")
four = four.reshape((1, 1, 36))
print(four, "\n-----")
four = four.reshape((2, 3, 3, 2))
print(four, "\n------------")

print("Five\n------------")
five = five.reshape((12, 2))
print(five, "\n-----")
five = five.reshape((1, 1, 24))
print(five, "\n-----")
five = five.reshape((1, -1, 12, 1))
print(five, "\n------------")

One
------------
[[1]
 [1]
 [1]
 [1]
 [1]] 
-----
[[[1]]

 [[1]]

 [[1]]

 [[1]]

 [[1]]] 
-----
[[[[1]]]


 [[[1]]]


 [[[1]]]


 [[[1]]]


 [[[1]]]] 
------------
Two
------------
[[1 1 1 1 1]] 
-----
[[[1]
  [1]
  [1]
  [1]
  [1]]] 
-----
[[[[1 1 1 1 1]]]] 
------------
Three
------------
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]] 
-----
[[[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]]] 
-----
[[[[1 1 1 1 1 1 1 1 1 1]
   [1 1 1 1 1 1 1 1 1 1]]]] 
------------
Four
------------
[[1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]] 
-----
[[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
   1]]] 
-----
[[[[1 1]
   [1 1]
   [1 1]]

  [[1 1]
   [1 1]
   [1 1]]

  [[1 1]
   [1 1]
   [1 1]]]


 [[[1 1]
   [1 1]
   [1 1]]

  [[1 1]
   [1 1]
   [1 1]]

  [[1 1]
   [1 1]
   [1 1]]]] 
------------
Five
------------
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 

Задание 4.

Для вектора ниже посчитайте его
* Максимум по 1 оси
* Минимум по 0 оси
* Сумму по всем осям
* Среднее по 0 оси
* Медиану по 1 оси

In [ ]:
v = np.random.randint(0, 9, size=(5, 7))

In [ ]:
mx_first_axis = v.max(axis=1) # максимум в каждой строке
mn_zero_axis = v.min(axis=0) # минимум в каждом столбике
sm_all_axis = v.sum() # сумма всех элементов
mean_zero_axis = v.mean(axis=0) # среднее в каждом столбике
median_first_axis = np.median(v, axis=1) # медиана в каждой строке

print("Максимум по 1 оси: ", mx_first_axis)
print("Минимум по 0 оси: ", mn_zero_axis)
print("Сумму по всем осям: ", sm_all_axis)
print("Среднее по 0 оси: ", mean_zero_axis)
print("Медиану по 1 оси: ", median_first_axis)

Максимум по 1 оси:  [6 6 8 7 8]
Минимум по 0 оси:  [1 0 2 1 3 1 0]
Сумму по всем осям:  131
Среднее по 0 оси:  [4.2 3.2 3.2 3.4 5.  4.4 2.8]
Медиану по 1 оси:  [5. 3. 3. 5. 5.]


Задание 5.

Для всё того же вектора `v` выведите
* Его shape
* 0 компоненту его "формы"
* 1 компоненту его "формы"

In [ ]:
print(v.shape) # форма
print(v.shape[0]) # нулевая компонента формы
print(v.shape[1]) # первая компонента формы

(5, 7)
5
7


Задание 6.

Для этого же вектора выведите
* Все числа больше 5
* Все числа меньше 7 в обратном порядке
* Все числа больше 3, которые делятся на 4 без остатка
* Все числа, остаток от деления на 5 которых равен 3
* Индекс максимума
* Индекс минимума
* Cписок с индексами элементов отсортированного массива в исходном (неотсортированном)

In [ ]:
print(v)
print("------------")
print(v[v > 5])
print("------------")
print(v[v < 7][::-1])
print("------------")
print(v[(v > 3) & (v % 4 == 0)])
print("------------")
print(v[v % 5 == 3])
print("------------")
print(v.argmax()) # индекс от первого встречного максимума
print("------------")
print(v.argmin()) # индекс от первого встречного минимума
print("------------")

v = v.argsort()
print(v)

[[1 3 5 2 0 4 6]
 [1 3 6 2 4 5 0]
 [6 0 2 1 5 4 3]
 [3 6 2 0 4 5 1]
 [2 0 4 1 6 3 5]]
------------
[6 6 6 6 6]
------------
[5 3 6 1 4 0 2 1 5 4 0 2 6 3 3 4 5 1 2 0 6 0 5 4 2 6 3 1 6 4 0 2 5 3 1]
------------
[4 4 4 4 4]
------------
[3 3 3 3 3]
------------
6
------------
4
------------
[[4 0 3 1 5 2 6]
 [6 0 3 1 4 5 2]
 [1 3 2 6 5 4 0]
 [3 6 2 0 4 5 1]
 [1 3 0 5 2 6 4]]


Задание 7.

Выполните следующие операции над вектором (независимо, не обязательно делать это в последовательности):
* Умножьте его на 3
* Разделите на 7
* Возведите в степень $\frac{2}{3}$
* Посчитайте $\sin$ от него
* Посчитайте $\log$ от него

In [ ]:
print(v * 3)
print("------------")
print(v / 7)
print("------------")
print(v ** (2/3))
print("------------")
print(np.sin(v))
print("------------")
print(np.log(v)) # логарифм натуральный по умолчанию

[[12  0  9  3 15  6 18]
 [18  0  9  3 12 15  6]
 [ 3  9  6 18 15 12  0]
 [ 9 18  6  0 12 15  3]
 [ 3  9  0 15  6 18 12]]
------------
[[0.57142857 0.         0.42857143 0.14285714 0.71428571 0.28571429
  0.85714286]
 [0.85714286 0.         0.42857143 0.14285714 0.57142857 0.71428571
  0.28571429]
 [0.14285714 0.42857143 0.28571429 0.85714286 0.71428571 0.57142857
  0.        ]
 [0.42857143 0.85714286 0.28571429 0.         0.57142857 0.71428571
  0.14285714]
 [0.14285714 0.42857143 0.         0.71428571 0.28571429 0.85714286
  0.57142857]]
------------
[[2.5198421  0.         2.08008382 1.         2.92401774 1.58740105
  3.30192725]
 [3.30192725 0.         2.08008382 1.         2.5198421  2.92401774
  1.58740105]
 [1.         2.08008382 1.58740105 3.30192725 2.92401774 2.5198421
  0.        ]
 [2.08008382 3.30192725 1.58740105 0.         2.5198421  2.92401774
  1.        ]
 [1.         2.08008382 0.         2.92401774 1.58740105 3.30192725
  2.5198421 ]]
------------
[[-0.7568025   0.  

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


### Разные инициализации + индексирование (3 балла)

Задание 8.

Необходимо построить квадрат $3 \times 3$ из нечётных чисел

In [ ]:
square = np.arange(1, 19, 2).reshape((3, 3))
square

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Задание 9.

Необходимо построить квадрат $4 \times 4$ из четных чисел в обратном порядке

In [ ]:
square = np.arange(32, 0, -2).reshape((4, 4))
square

array([[32, 30, 28, 26],
       [24, 22, 20, 18],
       [16, 14, 12, 10],
       [ 8,  6,  4,  2]])

Задание 10.

Необходимо построить сетку координат $11 \times 11$ с точкой $(0,0)$ в центре и шагом $0.1$ между клетками

In [ ]:
square = np.round_(np.arange(-6.0, 6.1, 0.1).reshape(11, -1), decimals=1) # возможно не совсем понял задачу, могу исправить при необходимости
square

array([[-6. , -5.9, -5.8, -5.7, -5.6, -5.5, -5.4, -5.3, -5.2, -5.1, -5. ],
       [-4.9, -4.8, -4.7, -4.6, -4.5, -4.4, -4.3, -4.2, -4.1, -4. , -3.9],
       [-3.8, -3.7, -3.6, -3.5, -3.4, -3.3, -3.2, -3.1, -3. , -2.9, -2.8],
       [-2.7, -2.6, -2.5, -2.4, -2.3, -2.2, -2.1, -2. , -1.9, -1.8, -1.7],
       [-1.6, -1.5, -1.4, -1.3, -1.2, -1.1, -1. , -0.9, -0.8, -0.7, -0.6],
       [-0.5, -0.4, -0.3, -0.2, -0.1, -0. ,  0.1,  0.2,  0.3,  0.4,  0.5],
       [ 0.6,  0.7,  0.8,  0.9,  1. ,  1.1,  1.2,  1.3,  1.4,  1.5,  1.6],
       [ 1.7,  1.8,  1.9,  2. ,  2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7],
       [ 2.8,  2.9,  3. ,  3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8],
       [ 3.9,  4. ,  4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9],
       [ 5. ,  5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ]])

Задание 11.

Замощение сетки $8\times8$ при помощи $0$ и $1$ в шахматном порядке, клетка с индексом $(0,0)$ замощается $1$

In [ ]:
vec = np.array([1, 0, 1, 0, 1, 0, 1, 0])
vec = np.vstack([vec, vec[::-1]])
vec = np.concatenate((vec, vec, vec, vec))

print(vec)
# (0, 0) берётся левый верх

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


Задание 12.

То же замощение, но клетка с индексом $(0,0)$ замощается $0$

In [ ]:
vec = np.array([0, 1, 0, 1, 0, 1, 0, 1])
vec = np.vstack([vec, vec[::-1]])
vec = np.concatenate((vec, vec, vec, vec))

print(vec)
# (0, 0) берётся левый верх

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Задание 13.

Необходимо построить нижне-треугольную матрицу переменного размера (задается передачей параметра в функцию). Это единичная матрица,замощённая $1$ под главной диагональю

In [ ]:
def create_triag_matrix_under_main_diag(shape_x, shape_y):
  if shape_x >= 0 and shape_y >= 0:
    triag_matrix = np.tri(shape_x, shape_y)

  return triag_matrix

shp_x = int(input("Введите размер x: "))
shp_y = int(input("Введите размер y: "))

result = create_triag_matrix_under_main_diag(shp_x, shp_y)
result

Введите размер x: 10
Введите размер y: 10


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Задание 14.

Необходимо построить верхне-треугольную матрицу переменного размера. Это единичная матрица, замощённая $1$ над главной диагональю

In [ ]:
def create_triag_matrix_upper_main_diag(shape_x, shape_y):
  if shape_x >= 0 and shape_y >= 0:
    triag_matrix = np.tri(shape_x, shape_y).T

  return triag_matrix

shp_x = int(input("Введите размер x: "))
shp_y = int(input("Введите размер y: "))

result = create_triag_matrix_upper_main_diag(shp_x, shp_y)
result

Введите размер x: 10
Введите размер y: 10


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Задание 15.

Необходимо построить матрицу, в которой единицы стоят на побочной диагонали (идущей из левого нижнего угла в правый верхний), в остальных местах стоят $0$

In [ ]:
result = np.eye(10)[::-1] # функция на ввод размера не запрашивалась по заданию, при необходимости могу добавить
result

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### Операции + аггрегации (3 балла)

Задание 16.

Дана выборка $\{X_i\}$ некоторой случайной величины $X$, необходимо оценить
* Математическое ожидание $E[X] = \frac{1}{N}\sum_{i=1}^N X_i$ этой случайной величины
* Дисперсию $D[X] = \frac{1}{N}\sum_{i=1}^N (X_i - E[X])^2$ этой случайной величины

In [ ]:
def expected_value(x):
    assert len(x) > 0
    return sum(x) / len(x)


def dispersion(x):
    assert len(x) > 0
    d = 0
    e = expected_value(x)
    for x_i in x:
        d += (x_i - e) ** 2
    return d / len(x)

In [ ]:
def expected_value_np(x):
    return x.sum() / x.size

In [ ]:
def dispersion_np(x):
    return ((x - expected_value_np(x)) ** 2).sum() / x.size

In [ ]:
np.testing.assert_array_equal(expected_value([1]), expected_value_np(np.array([1])))
np.testing.assert_array_equal(expected_value([3, 4]), expected_value_np(np.array([3, 4])))
np.testing.assert_array_equal(expected_value([-1, 0, 1]), expected_value_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(expected_value([-99, -98]), expected_value_np(np.array([-99, -98])))

np.testing.assert_array_equal(dispersion([1]), dispersion_np(np.array([1])))
np.testing.assert_array_equal(dispersion([3, 4]), dispersion_np(np.array([3, 4])))
np.testing.assert_array_equal(dispersion([-1, 0, 1]), dispersion_np(np.array([-1, 0, 1])))
np.testing.assert_array_equal(dispersion([-99, -98]), dispersion_np(np.array([-99, -98])))

Задание 17.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое квадратов разностей их значений

In [ ]:
def mean_square_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    # Здесь и далее эти проверки !не нужно! дублировать в свои функции; Здесь они для того, чтобы лишний раз подчеркнуть валидность входных данных
    s = 0
    for i in range(len(y1)):
        s += (y1[i] - y2[i]) ** 2
    return s / len(y1)

In [ ]:
def mean_square_difference_np(y1, y2):
    return ((y1 - y2) ** 2).sum() / y1.size

In [ ]:
assert mean_square_difference([1], [1]) == mean_square_difference_np(np.array([1]), np.array([1]))
assert mean_square_difference([1, 2], [1, 2]) == mean_square_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_square_difference([-1, 1], [0, 0]) == mean_square_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_square_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_square_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 18.

Даны два вектора $y_1$ и $y_2$, нужно посчитать среднее арифметическое модулей разностей их значений

In [ ]:
def mean_abs_difference(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    s = 0
    for i in range(len(y1)):
        s += abs(y1[i] - y2[i])
    return s / len(y1)

In [ ]:
def mean_abs_difference_np(y1, y2):
    return (np.absolute(y1 - y2)).sum() / y1.size

In [ ]:
assert mean_abs_difference([1], [1]) == mean_abs_difference_np(np.array([1]), np.array([1]))
assert mean_abs_difference([1, 2], [1, 2]) == mean_abs_difference_np(np.array([1, 2]), np.array([1, 2]))
assert mean_abs_difference([-1, 1], [0, 0]) == mean_abs_difference_np(np.array([-1, 1]), np.array([0, 0]))
assert mean_abs_difference([-3, -2, 0, 1, 4], [-2, -2, -1, -1, 5]) == mean_abs_difference_np(np.array([-3, -2, 0, 1, 4]), np.array([-2, -2, -1, -1, 5]))

Задание 19.

Даны два вектора $y_1$ и $y_2$, в которых присутствуют только $0$ и $1$. Необходимо посчитать вероятность совпадения - в скольких точках значения двух векторов совпадают

In [ ]:
def matching_proba(y1, y2):
    assert len(y1) == len(y2) and len(y1) > 0
    assert len(set(y1)) <= 2
    assert len(set(y2)) <= 2
    assert 0 in set(y1) or 1 in set(y1) or (0 in set(y1) and 1 in set(y1))
    assert 0 in set(y2) or 1 in set(y2) or (0 in set(y2) and 1 in set(y2))

    return sum([y1[i] == y2[i] for i in range(len(y1))]) / len(y1)

In [ ]:
def matching_proba_np(y1, y2):
    return (y1 == y2).sum() / y1.size

In [ ]:
np.testing.assert_array_equal(matching_proba([0, 1], [1, 0]), matching_proba_np(np.array([0, 1]), np.array([1, 0])))
np.testing.assert_array_equal(matching_proba([0, 1, 0, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 1, 0, 1]), np.array([0, 0, 1, 1])))
np.testing.assert_array_equal(matching_proba([0, 0, 1, 1], [0, 0, 1, 1]), matching_proba_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1])))

Задание 20.

Даны два вектора: $y_1$, $y_2$. В $y_1$ и $y_2$ присутствуют только $0$ и $1$.

Необходимо найти границы (индексы), такие, что если мы разделим вдоль какой-то из этих границ оба вектора на две части, то
* в левой части пересекающихся в $y_1$ и $y_2$ нулей будет строго больше, чем пересекающихся единиц или непересекающихся элементов
* в правой - пересекающихся единиц строго больше, чем пересекающихся нулей или непересекающихся элементов.

Если какая-то из частей не содержит элементов вовсе, то будем считать, что она подходит под условие.

In [ ]:
def find_thresholds(y1, y2, debug=False):
    assert len(y1) == len(y2) and len(y1) > 0
    n = len(y1)
    matching_zeros = [1 if y1[i] == y2[i] == 0 else 0 for i in range(n)]
    matching_ones = [1 if y1[i] == y2[i] == 1 else 0 for i in range(n)]
    res = []
    if sum(matching_ones) / n > 0.5:
        res.append(0)
    for i in range(1, n):
        if debug: # если вам непонятна логика работы этой функции, передайте третьим аргументом True
            print(matching_zeros[:i], matching_ones[i:], i)
        if sum(matching_zeros[:i]) / i > 0.5 and sum(matching_ones[i:]) / (n - i) > 0.5:
            res.append(i)
    if sum(matching_zeros) / n > 0.5:
        res.append(n)
    return res

In [ ]:
def find_thresholds_np(y1, y2, debug=False):
  y1 = (y1 == 0) * (y2 == 0)
  y2 = (y2 == 1) * (y2 == 1)
  i = np.arange(1, y1.size + 1)
  res = np.array([], dtype=int)

  if np.sum(y2) / y1.size > 0.5:
    res = np.append(res, 0)

  result = (((np.cumsum(y1) / i) > 0.5) & ((np.sum(y2) - np.cumsum(y2)) / (y1.size - i) > 0.5))
  result = np.where(result == True, result * 0 + i, 0)
  result = result[result > 0]

  res = np.append(res, result)

  if np.sum(y1) / y1.size > 0.5:
    res = np.append(res, y1.size)

  return res



In [ ]:
np.testing.assert_array_equal(find_thresholds([0], [0]), find_thresholds_np(np.array([0]), np.array([0])))
np.testing.assert_array_equal(find_thresholds([1], [1]), find_thresholds_np(np.array([1]), np.array([1])))
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 1], [0, 0, 1, 1]), 
    find_thresholds_np(np.array([0, 0, 1, 1]), np.array([0, 0, 1, 1]))
)
np.testing.assert_array_equal(
    find_thresholds([0, 0, 1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1]),
    find_thresholds_np(np.array([0, 0, 1, 0, 0, 1, 1, 1]), np.array([0, 0, 0, 0, 0, 1, 1, 1]))
)

### Разные действия с матрицами (3 балла)

Задание 21.

Дана матрица размера $(32, 3, 16, 16)$, заполненная случайными числами от 0 до 9. При помощи **ровно двух** преобразований приведите её к виду $(32, 1)$. При выполнении задания **можно** создавать вспомогательные матрицы!

In [ ]:
data = np.random.randint(0, 10, size=(32, 3, 16, 16))
vspom = np.ones(768).reshape((768, 1))

data.shape = 32, 768
data = np.matmul(data, vspom)

assert data.shape == (32, 1)

Задание 22.

Даны две матрицы $m_1$ размером $(32, 256)$ и $m_2$ размером $(32, 512)$, а также две вспомогательные матрицы $W_1$ размером $(256, 32)$ и $W_2$ размером $(512, 16)$. Используя **все** данные матрицы, сделайте так, чтобы на выходе получилась **ровно одна** матрица размером $(32, 32)$

In [ ]:
from numpy.core.multiarray import result_type
m1 = np.random.randint(0, 10, size=(32, 256))
m2 = np.random.randint(0, 10, size=(32, 512))
W1 = np.random.randint(0, 10, size=(256, 32))
W2 = np.random.randint(0, 10, size=(512, 16))

result = np.matmul(m1.transpose(), m2)
result = np.matmul(result.transpose(), W1)
result = np.matmul(result.transpose(), W2)
result = np.matmul(W2, result.transpose())
result = np.matmul(m2, result)

assert result.shape == (32, 32)

Задание 23.

Приведите полученную на последнем шаге матрицу к виду $(32, 3)$ и сделайте так, чтобы все значения в этой матрице были в промежутке от $0$ до $1$

In [ ]:
# Вжух! (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
result = np.absolute(np.sin(np.matmul(result, np.ones((32, 3)))))
result.shape

assert result.shape == (32, 3)
assert ((result >= 0) & (result <= 1)).all()