# ML T-Generation Занятие 2: Data Wrangling Основы работы с векторными данными и визуализацией. NumPy

## Пример задач

Давайте рассмотрим пример решения одной из задач на сайте kaggle и постараемся ее проанализировать.


https://www.kaggle.com/madhulekha/a-comprehensive-solution-to-your-first-ml-problem

Как видите, изучение данных и генерация признаков занимает большую часть решения. Это нормально.

## Numpy

Библиотека предназаченная для работы с массивами. Очевидный вопрос-почему не встроенные массивы python. Давайте сразу на примере посмотрим, почему

In [1]:
import numpy as np

In [2]:
%timeit [i**2 for i in range(1000)]

1000 loops, best of 5: 268 µs per loop


In [3]:
%timeit np.arange(1000)**2

The slowest run took 1330.62 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 2.84 µs per loop


Разница существенная

### Справка

В 1995 году программист Jim Hugunin написал библиотеку Numeric для языка Python. Библиотека развивалась при участии многих людей, среди которых были Jim Fulton, David Ascher, Paul DuBois и Konrad Hinsen. Библиотека доступна по сей день, считается вполне стабильной и полной, но устаревшей.

Предлагалось добавить Numeric в стандартную библиотеку языка Python, но Гвидо Ван Россум (автор Python) чётко дал понять, что код в его тогдашнем состоянии было невозможно поддерживать.

Кроме того, библиотека Numeric медленно обрабатывала большие массивы данных.

На основе библиотеки Numeric была создана библиотека NumArray. Код Numeric был полностью переписан.

Библиотека NumArray обрабатывала большие массивы данных быстрее библиотеки Numeric, но малые массивы обрабатывала медленнее.

Некоторое время использовалась и библиотека Numeric, и библиотека NumArray. Последняя версия Numeric (v24.2) была выпущена 11 ноября 2005 года. Последняя версия NumArray (v1.5.2) вышла 24 августа 2006 года. Библиотека NumArray более не рекомендуется к использованию.

В начале 2005 года программист Трэвис Олифант захотел объединить сообщество вокруг одного проекта и для замены библиотек Numeric и NumArray создал библиотеку NumPy. NumPy был создан на основе кода Numeric. Код Numeric был переписан так, чтобы его было легче поддерживать, и в библиотеку можно было добавить новые возможности. Возможности NumArray были добавлены в NumPy.

Изначально NumPy был частью библиотеки SciPy. Чтобы позволить другим проектам использовать библиотеку NumPy, её код был помещён в отдельный пакет.

Исходный код NumPy находится в открытом доступе. Существует большое количество документации. Имеется даже подробный «Путеводитель по NumPy».

NumPy v1.3.0 выпущен 5 апреля 2009 года и поддерживает Python v2.6. Поддержка Python v3 была добавлена начиная с версии 1.5.0.

http://www.numpy.org

### Шпаргалка

В Numpy большой набор стандартных функций, которые помогают реализовывать даже самые сложные операции. Для того что бы не тратить время на написание собственных функций, будет полезно иметь шпаргалку с основными полезными

In [ ]:
from IPython.display import Image
Image('numpy.png') 

In [ ]:
# немного хитростей jupyter - двойным табом, можно вызвать документацию
# np.

In [5]:
a = np.array([1,3,4,5])
a

array([1, 3, 4, 5])

смотрим размерность массива

In [6]:
a.ndim

1

In [9]:
# TASK: создать двумерный/трехмерный массив

arr1 = np.array([[1,3,4,5]])
arr2 = np.array([[[1,3,4,5]]])

print(arr1.ndim)
print(arr2.ndim)

2
3


In [10]:
b = np.array([[1,3,4,5],[1,3,4,5]])
b

array([[1, 3, 4, 5],
       [1, 3, 4, 5]])

### Создание массивов

**На практике мы редко добавляем элементы по одному и нужно создавать матрицу/массив нужной размерности**

- Равномерно распределенные элементы:

In [ ]:
a = np.arange(10) # 0 .. n-1  (!)
a

In [ ]:
b = np.arange(1, 11, 2) # начало, конец(не включая), шаг
b

- по числу элементов:

In [ ]:
c = np.linspace(0, 1, 6)   # начало, конец, количество точек
c

In [ ]:
d = np.linspace(0, 1, 5, endpoint=False)
d

- Часто встречающиеся массивы:

In [ ]:
a = np.ones((3, 3))  
a

In [ ]:
b = np.zeros((2, 2))
b

In [ ]:
c = np.eye(3)
c

In [ ]:
d = np.diag(np.array([1, 2, 3, 4]))
d

* `np.random` генерация случайных чисел:

In [ ]:
a = np.random.rand(4)
a  

In [ ]:
np.random.seed(42)
b = np.random.randn(10)
b  

### Основные типы данных NumPy

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])
a.dtype

Точка после числа означает, что это тип данных `float64`

In [ ]:
b = np.array([1., 2., 3.])
b.dtype

In [ ]:
c = np.array(["1", 2, 3])
c.dtype

In [ ]:
c[1]

In [ ]:
a = np.ones((3, 3))
a

In [ ]:
a

Прочие типы данных:

- Комплексные числа

In [ ]:
d = np.array([1+2j, 3+4j, 5+6*1j])
d.dtype

 - Bool

In [ ]:
e = np.array([True, False, False, True])
e.dtype

- Строки

На строки память выделяется "жадно" - по максимальному числу литер в строке. 
В этом примере на каждую строку выделяется по 7 литер, и тип данных - 'U7'

In [ ]:
f = np.array([(1,23,4), 'Hello', 'Hallo',])
f.dtype

### Индексирование массивов и срезы

В целом так же, как со встроенными последовательностями Python (например, как со списками).

**Индексирование**

In [ ]:
a = np.arange(10)
a

In [ ]:
a[0], a[2], a[-1]

Работает и популярный в Python способ отражения массива:

In [ ]:
a[::-1]

Для многомерных массивов индексы - это кортежи целых чисел. Кортеж, по сути - неизменяемый список.

In [ ]:
a = np.diag(np.arange(3))
a

In [ ]:
%timeit a[1, 1]

In [ ]:
%timeit a[1][1]

In [ ]:
a[2, 1] = 10 
a

In [ ]:
a[1]

**Срезы**

In [ ]:
a = np.arange(10)
a

In [ ]:
a[2:9:3] # [начало:конец:шаг]

Последний индекс не включается

In [ ]:
a[:4]

Можно совмещать присваивание и срез:

In [ ]:
a = np.arange(10)


In [ ]:
b = np.arange(5)
b

In [ ]:
a

In [ ]:
b[::-1]

In [ ]:
a[5:]

In [ ]:
np.random.seed(3)
a = np.random.randint(0, 20, 15)
a

In [ ]:
(a % 3 == 0)

In [ ]:
mask = (a % 3 == 0)
extract_from_a = a[mask] 
extract_from_a           

Индексирование маской может быть очень полезным для присваивания значений части элементов массива:

In [ ]:
a[a % 3 == 0] = -1
a

Индексирование массивом целых чисел

In [ ]:
a = np.arange(0, 100, 10)
a

In [ ]:
a[[2, 3, 2, 4, 2]]  # тут должен быть питоновский лист

In [ ]:
a[[9, 7]] = -100
a

In [ ]:
a = np.arange(10)
idx = np.array([[3, 4], [9, 7]])
idx.shape
idx

In [ ]:
a[idx]

### Умножение матриц и столбцов

In [ ]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])
r1 = np.dot(a, b)
r2 = a.dot(b)

print("Матрица A:\n", a)
print("Матрица B:\n", b)
print("Результат умножения функцией:\n", r1)
print("Результат умножения методом:\n", r2)

In [ ]:
a@b

Матрицы в `NumPy` можно умножать и на векторы:

In [ ]:
c = np.array([1, 2])
r3 = b.dot(c)

print("Матрица:\n", b)
print("Вектор:\n", c)
print("Результат умножения:\n", r3)

__Обратите внимание:__ операция __`*`__ производит над матрицами покоординатное умножение, а не матричное!

In [ ]:
r = a * b

print("Матрица A:\n", a)
print("Матрица B:\n", b)
print("Результат покоординатного умножения через операцию *:\n", r)
a

Более подробно о матричном умножении в `NumPy`
см. [документацию](http://docs.scipy.org/doc/numpy-1.10.0/reference/routines.linalg.html#matrix-and-vector-products).

In [ ]:
# Задание: написать функции выводящие минимум для массива, сумму


In [14]:
print(a.min())
print(a.max())
print(a.sum())

0
1
2


In [ ]:
a = np.array([1,2,3])


# Внимание. Самостоятельная работа

# Задание по numpy

In [24]:
# 0. Создать нулевой вектор с 5 значений на 5 позиции 5
# Ваш код здесь

# не понял задания. Решил так: создать нулевой массив размера 5, где на 5 позиции стоит 5

mat = np.zeros(5)
mat[4] = 5

mat

array([0., 0., 0., 0., 5.])

In [17]:
# 1. Создать матрицу 3*3 со значениями от 0 до 8
np.arange(0, 9).reshape((3, 3))


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
# 2. Найти индексы не нулевых элементов в массиве [1,2,0,0,4,0]

a = np.array([1,2,0,0,4,0])

np.nonzero(a)


(array([0, 1, 4]),)

In [22]:
# 3. Матрица 3*3*3 с рандомными значениями
# Ваш код здесь

np.random.random((3, 3, 3))

array([[[0.89788935, 0.45593971, 0.66946807],
        [0.31617293, 0.22884309, 0.7173241 ],
        [0.41897699, 0.03433921, 0.67708463]],

       [[0.7126689 , 0.22017783, 0.00863789],
        [0.64375319, 0.36298449, 0.8034309 ],
        [0.03060712, 0.75348363, 0.57097814]],

       [[0.57462923, 0.28380165, 0.27918132],
        [0.34360537, 0.29029183, 0.22672873],
        [0.45613593, 0.77098021, 0.23160673]]])

In [23]:
# 4. Матриа 10 на 10, найти минимумы и максимумы
# Ваш код здесь

mat = np.random.random((10, 10))

print(mat.min())
print(mat.max())

0.029837264835609334
0.9928278871013254
